export const sampleData = {
  professors: [
    { id: 'p1', name: 'أ.د. حاتم خاطر' },
    { id: 'p2', name: 'أ.م.د. مروة البغدادي' },
    { id: 'p3', name: 'د. جلال جويدة' },
    { id: 'p4', name: 'د. رحاب المرسى' },
    { id: 'p5', name: 'د. غادة ربيع' },
    { id: 'p6', name: 'د. ماجدة رياض' },
    { id: 'p7', name: 'أ.م.د. عمرو يوسف' },
    { id: 'p8', name: 'د. رشدي محمد' },
    { id: 'p9', name: 'أ.م.د. مرفت نصري' },
    { id: 'p10', name: 'أ.م.د. محمود فاروق' },
    { id: 'p11', name: 'د. وائل الغريب' },
    { id: 'p12', name: 'أ.م.د. محمد مصطفى' },
    { id: 'p13', name: 'أ.م.د. ابراهيم رجب' },
    { id: 'p14', name: 'د. أحمد سعيد' },
    { id: 'p15', name: 'د. نهى كمال' },
    { id: 'p16', name: 'أ.م.د. محمد علي' },
    { id: 'p17', name: 'د. سامية الشرقاوي' },
    { id: 'p18', name: 'أ.د. أيمن حسن' },
    { id: 'p19', name: 'د. هبة الزهراء' },
    { id: 'p20', name: 'أ.م.د. خالد منصور' },
    { id: 'p21', name: 'د. منى عبدالله' },
    { id: 'p22', name: 'أ.م.د. طارق السيد' },
    { id: 'p23', name: 'د. ليلى إبراهيم' },
    { id: 'p24', name: 'أ.د. عصام حافظ' },
    { id: 'p25', name: 'د. أمل رفاعي' },
    { id: 'p26', name: 'أ.م.د. حسام الدين' },
    { id: 'p27', name: 'د. مصطفى العوضي' },
    { id: 'p28', name: 'أ.م.د. سلوى الجمل' },
    { id: 'p29', name: 'د. علاء الدين' },
    { id: 'p30', name: 'أ.م.د. دينا الشافعي' },
    { id: 'p31', name: 'د. عادل خليل' },
    { id: 'p32', name: 'أ.م.د. شريف أحمد' },
    { id: 'p33', name: 'د. ندى حسين' },
    { id: 'p34', name: 'أ.د. كمال الأنصاري' },
    { id: 'p35', name: 'د. صفاء النجار' },
    { id: 'p36', name: 'أ.م.د. ياسمين حلمي' },
    { id: 'p37', name: 'د. محمد الأزهري' },
    { id: 'p38', name: 'أ.م.د. ريم الحسن' },
    { id: 'p39', name: 'د. خالد الشيخ' },
    { id: 'p40', name: 'أ.م.د. حنان قاسم' },
    { id: 'p41', name: 'د. سميرة التركي' },
    { id: 'p42', name: 'أ.م.د. عبدالرحمن مرسي' },
    { id: 'p43', name: 'د. رانيا فتحي' },
    { id: 'p44', name: 'أ.د. نادر الحلواني' },
  ],

  locations: [
    { id: 'l1', name: 'online', capacity: 72, type: 'online' },
    { id: 'l2', name: 'مدرج د. عادل', capacity: 72, type: 'lecture' },
    { id: 'l3', name: 'مدرج د. فاروق', capacity: 72, type: 'lecture' },
    { id: 'l4', name: 'قاعة 20', capacity: 72, type: 'classroom' },
    { id: 'l5', name: 'قاعة 4', capacity: 72, type: 'classroom' },
    { id: 'l6', name: 'قاعة 3', capacity: 72, type: 'classroom' },
    { id: 'l7', name: 'قاعة 1', capacity: 72, type: 'classroom' },
    { id: 'l8', name: 'قاعة 2', capacity: 72, type: 'classroom' },
    { id: 'l9', name: 'قاعة 5', capacity: 72, type: 'classroom' },
    { id: 'l10', name: 'قاعة 6', capacity: 72, type: 'classroom' },
    { id: 'l11', name: 'قاعة 10', capacity: 72, type: 'classroom' },
    { id: 'l12', name: 'قاعة 15', capacity: 72, type: 'classroom' },
    { id: 'l13', name: 'معمل 1', capacity: 72, type: 'lab' },
    { id: 'l14', name: 'معمل 2', capacity: 72, type: 'lab' },
    { id: 'l15', name: 'معمل 3', capacity: 72, type: 'lab' },
    { id: 'l16', name: 'قاعة 7', capacity: 72, type: 'classroom' },
    { id: 'l17', name: 'قاعة 8', capacity: 72, type: 'classroom' },
    { id: 'l18', name: 'قاعة 9', capacity: 72, type: 'classroom' },
    { id: 'l19', name: 'قاعة 11', capacity: 72, type: 'classroom' },
    { id: 'l20', name: 'قاعة 12', capacity: 72, type: 'classroom' },
    { id: 'l21', name: 'مدرج رئيسي', capacity: 72, type: 'lecture' },
    { id: 'l22', name: 'مدرج ب', capacity: 72, type: 'lecture' },
    { id: 'l23', name: 'معمل 4', capacity: 72, type: 'lab' },
  ],

  subjects: [
    { id: 's1', name: 'حقوق انسان', code: 'HUM101' },
    { id: 's2', name: 'رياضيات الاعمال', code: 'MTH101' },
    { id: 's3', name: 'سلوك تنظيمي', code: 'MGT201' },
    { id: 's4', name: 'طرق ومهارات الاتصال', code: 'COM101' },
    { id: 's5', name: 'التفكير الابتكاري', code: 'INN101' },
    { id: 's6', name: 'مبادئ علوم سياسية', code: 'POL101' },
    { id: 's7', name: 'مبادئ المحاسبة', code: 'ACC101' },
    { id: 's8', name: 'نظم المعلومات الإدارية', code: 'MIS301' },
    { id: 's9', name: 'إدارة الأعمال', code: 'MGT101' },
    { id: 's10', name: 'اقتصاد كلي', code: 'ECO101' },
    { id: 's11', name: 'إحصاء', code: 'STA201' },
    { id: 's12', name: 'بحوث العمليات', code: 'OPR301' },
    { id: 's13', name: 'قانون تجاري', code: 'LAW201' },
    { id: 's14', name: 'إدارة مالية', code: 'FIN301' },
    { id: 's15', name: 'تسويق', code: 'MKT201' },
    { id: 's16', name: 'إدارة الإنتاج', code: 'PRD301' },
    { id: 's17', name: 'قواعد البيانات', code: 'DB301' },
    { id: 's18', name: 'برمجة', code: 'PRG201' },
    { id: 's19', name: 'تحليل نظم', code: 'SYS301' },
    { id: 's20', name: 'محاسبة تكاليف', code: 'ACC201' },
    { id: 's21', name: 'مقدمة في نظم المعلومات', code: 'IS101' },
    { id: 's22', name: 'شبكات الحاسوب', code: 'NET201' },
    { id: 's23', name: 'أمن المعلومات', code: 'SEC301' },
    { id: 's24', name: 'إدارة المشاريع', code: 'PM301' },
    { id: 's25', name: 'اقتصاد جزئي', code: 'ECO102' },
  ],

  groups: [
    { id: 'g1', year: 'الفرقة الأولى', major: 'نظم معلومات الاعمال', section: 'مجموعة (A)' },
    { id: 'g2', year: 'الفرقة الأولى', major: 'نظم معلومات الاعمال', section: 'مجموعة (B)' },
    { id: 'g3', year: 'الفرقة الأولى', major: 'نظم المعلومات الادارية', section: 'مجموعة (A)' },
    { id: 'g4', year: 'الفرقة الأولى', major: 'نظم المعلومات الادارية', section: 'مجموعة (B)' },
    { id: 'g5', year: 'الفرقة الأولى', major: 'محاسبة ومراجعة (انجليزي) (لائحة قديمة)', section: 'مجموعة (A)' },
    { id: 'g6', year: 'الفرقة الثانية', major: 'نظم معلومات الاعمال', section: 'مجموعة (A)' },
    { id: 'g7', year: 'الفرقة الثانية', major: 'نظم معلومات الاعمال', section: 'مجموعة (B)' },
    { id: 'g8', year: 'الفرقة الثانية', major: 'نظم المعلومات الادارية', section: 'مجموعة (A)' },
    { id: 'g9', year: 'الفرقة الثانية', major: 'نظم المعلومات الادارية', section: 'مجموعة (B)' },
    { id: 'g10', year: 'الفرقة الثانية', major: 'محاسبة ومراجعة (انجليزي) (لائحة قديمة)', section: 'مجموعة (A)' },
    { id: 'g11', year: 'الفرقة الثالثة', major: 'نظم معلومات الاعمال', section: 'مجموعة (A)' },
    { id: 'g12', year: 'الفرقة الثالثة', major: 'نظم معلومات الاعمال', section: 'مجموعة (B)' },
    { id: 'g13', year: 'الفرقة الثالثة', major: 'نظم المعلومات الادارية', section: 'مجموعة (A)' },
    { id: 'g14', year: 'الفرقة الثالثة', major: 'محاسبة ومراجعة (انجليزي) (لائحة قديمة)', section: 'مجموعة (A)' },
    { id: 'g15', year: 'الفرقة الرابعة', major: 'نظم معلومات الاعمال', section: 'مجموعة (A)' },
    { id: 'g16', year: 'الفرقة الرابعة', major: 'نظم معلومات الاعمال', section: 'مجموعة (B)' },
    { id: 'g17', year: 'الفرقة الرابعة', major: 'نظم المعلومات الادارية', section: 'مجموعة (A)' },
    { id: 'g18', year: 'الفرقة الرابعة', major: 'محاسبة ومراجعة (انجليزي) (لائحة قديمة)', section: 'مجموعة (A)' },
  ],

  lectures: [
    // --- Group g1: الفرقة الأولى / نظم معلومات الاعمال / مجموعة (A) ---
    { id: 'lec1', subjectId: 's1', professorId: 'p7', locationId: 'l2', groupId: 'g1', day: 'السبت', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec2', subjectId: 's2', professorId: 'p5', locationId: 'l2', groupId: 'g1', day: 'السبت', startHour: 11, duration: 1, type: 'محاضرة' },
    { id: 'lec3', subjectId: 's3', professorId: 'p8', locationId: 'l2', groupId: 'g1', day: 'الأحد', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec4', subjectId: 's4', professorId: 'p9', locationId: 'l2', groupId: 'g1', day: 'الأحد', startHour: 11, duration: 1, type: 'محاضرة' },
    { id: 'lec5', subjectId: 's5', professorId: 'p10', locationId: 'l2', groupId: 'g1', day: 'الأحد', startHour: 13, duration: 1, type: 'محاضرة' },
    { id: 'lec6', subjectId: 's6', professorId: 'p3', locationId: 'l3', groupId: 'g1', day: 'الأربعاء', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec7', subjectId: 's9', professorId: 'p18', locationId: 'l4', groupId: 'g1', day: 'الثلاثاء', startHour: 8, duration: 1, type: 'محاضرة' },
    { id: 'lec8', subjectId: 's10', professorId: 'p1', locationId: 'l4', groupId: 'g1', day: 'الخميس', startHour: 9, duration: 1, type: 'محاضرة' },

    // --- Group g2: الفرقة الأولى / نظم معلومات الاعمال / مجموعة (B) ---
    { id: 'lec9', subjectId: 's1', professorId: 'p7', locationId: 'l3', groupId: 'g2', day: 'السبت', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec10', subjectId: 's2', professorId: 'p5', locationId: 'l3', groupId: 'g2', day: 'السبت', startHour: 12, duration: 1, type: 'محاضرة' },
    { id: 'lec11', subjectId: 's3', professorId: 'p8', locationId: 'l3', groupId: 'g2', day: 'الاثنين', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec12', subjectId: 's4', professorId: 'p9', locationId: 'l3', groupId: 'g2', day: 'الاثنين', startHour: 11, duration: 1, type: 'محاضرة' },
    { id: 'lec13', subjectId: 's5', professorId: 'p10', locationId: 'l3', groupId: 'g2', day: 'الثلاثاء', startHour: 13, duration: 1, type: 'محاضرة' },
    { id: 'lec14', subjectId: 's6', professorId: 'p3', locationId: 'l2', groupId: 'g2', day: 'الأربعاء', startHour: 11, duration: 1, type: 'محاضرة' },
    { id: 'lec15', subjectId: 's9', professorId: 'p18', locationId: 'l4', groupId: 'g2', day: 'الثلاثاء', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec16', subjectId: 's10', professorId: 'p1', locationId: 'l4', groupId: 'g2', day: 'الخميس', startHour: 11, duration: 1, type: 'محاضرة' },

    // --- Group g3: الفرقة الأولى / نظم المعلومات الادارية / مجموعة (A) ---
    { id: 'lec17', subjectId: 's1', professorId: 'p7', locationId: 'l1', groupId: 'g3', day: 'السبت', startHour: 8, duration: 1, type: 'محاضرة' },
    { id: 'lec18', subjectId: 's2', professorId: 'p6', locationId: 'l1', groupId: 'g3', day: 'الأحد', startHour: 8, duration: 1, type: 'محاضرة' },
    { id: 'lec19', subjectId: 's9', professorId: 'p16', locationId: 'l1', groupId: 'g3', day: 'الاثنين', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec20', subjectId: 's4', professorId: 'p9', locationId: 'l1', groupId: 'g3', day: 'الاثنين', startHour: 11, duration: 1, type: 'محاضرة' },
    { id: 'lec21', subjectId: 's10', professorId: 'p25', locationId: 'l5', groupId: 'g3', day: 'الثلاثاء', startHour: 8, duration: 1, type: 'محاضرة' },
    { id: 'lec22', subjectId: 's25', professorId: 'p14', locationId: 'l5', groupId: 'g3', day: 'الخميس', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec23', subjectId: 's7', professorId: 'p17', locationId: 'l6', groupId: 'g3', day: 'الأربعاء', startHour: 10, duration: 1, type: 'محاضرة' },

    // --- Group g4: الفرقة الأولى / نظم المعلومات الادارية / مجموعة (B) ---
    { id: 'lec24', subjectId: 's1', professorId: 'p20', locationId: 'l1', groupId: 'g4', day: 'السبت', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec25', subjectId: 's2', professorId: 'p6', locationId: 'l1', groupId: 'g4', day: 'الأحد', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec26', subjectId: 's9', professorId: 'p16', locationId: 'l1', groupId: 'g4', day: 'الاثنين', startHour: 13, duration: 1, type: 'محاضرة' },
    { id: 'lec27', subjectId: 's25', professorId: 'p14', locationId: 'l6', groupId: 'g4', day: 'الثلاثاء', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec28', subjectId: 's7', professorId: 'p17', locationId: 'l6', groupId: 'g4', day: 'الأربعاء', startHour: 12, duration: 1, type: 'محاضرة' },

    // --- Group g5: الفرقة الأولى / محاسبة ---
    { id: 'lec29', subjectId: 's7', professorId: 'p19', locationId: 'l4', groupId: 'g5', day: 'السبت', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec30', subjectId: 's20', professorId: 'p21', locationId: 'l4', groupId: 'g5', day: 'الأحد', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec31', subjectId: 's13', professorId: 'p22', locationId: 'l4', groupId: 'g5', day: 'الاثنين', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec32', subjectId: 's10', professorId: 'p25', locationId: 'l4', groupId: 'g5', day: 'الثلاثاء', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec33', subjectId: 's2', professorId: 'p15', locationId: 'l5', groupId: 'g5', day: 'الأربعاء', startHour: 8, duration: 1, type: 'محاضرة' },

    // --- Group g6: الفرقة الثانية / نظم معلومات الاعمال / A ---
    { id: 'lec34', subjectId: 's11', professorId: 'p2', locationId: 'l2', groupId: 'g6', day: 'السبت', startHour: 8, duration: 1, type: 'محاضرة' },
    { id: 'lec35', subjectId: 's8', professorId: 'p12', locationId: 'l2', groupId: 'g6', day: 'السبت', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec36', subjectId: 's15', professorId: 'p4', locationId: 'l2', groupId: 'g6', day: 'الأحد', startHour: 8, duration: 1, type: 'محاضرة' },
    { id: 'lec37', subjectId: 's14', professorId: 'p26', locationId: 'l2', groupId: 'g6', day: 'الأحد', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec38', subjectId: 's17', professorId: 'p29', locationId: 'l13', groupId: 'g6', day: 'الثلاثاء', startHour: 9, duration: 2, type: 'معمل' },
    { id: 'lec39', subjectId: 's12', professorId: 'p32', locationId: 'l3', groupId: 'g6', day: 'الأربعاء', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec40', subjectId: 's18', professorId: 'p37', locationId: 'l14', groupId: 'g6', day: 'الخميس', startHour: 10, duration: 2, type: 'معمل' },
    { id: 'lec41', subjectId: 's16', professorId: 'p27', locationId: 'l3', groupId: 'g6', day: 'الخميس', startHour: 8, duration: 1, type: 'محاضرة' },

    // --- Group g7: الفرقة الثانية / نظم معلومات الاعمال / B ---
    { id: 'lec42', subjectId: 's11', professorId: 'p2', locationId: 'l3', groupId: 'g7', day: 'السبت', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec43', subjectId: 's8', professorId: 'p12', locationId: 'l3', groupId: 'g7', day: 'السبت', startHour: 11, duration: 1, type: 'محاضرة' },
    { id: 'lec44', subjectId: 's15', professorId: 'p4', locationId: 'l3', groupId: 'g7', day: 'الأحد', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec45', subjectId: 's14', professorId: 'p26', locationId: 'l3', groupId: 'g7', day: 'الأحد', startHour: 11, duration: 1, type: 'محاضرة' },
    { id: 'lec46', subjectId: 's17', professorId: 'p29', locationId: 'l13', groupId: 'g7', day: 'الثلاثاء', startHour: 11, duration: 2, type: 'معمل' },
    { id: 'lec47', subjectId: 's12', professorId: 'p32', locationId: 'l4', groupId: 'g7', day: 'الأربعاء', startHour: 11, duration: 1, type: 'محاضرة' },
    { id: 'lec48', subjectId: 's18', professorId: 'p37', locationId: 'l14', groupId: 'g7', day: 'الخميس', startHour: 12, duration: 2, type: 'معمل' },

    // --- Group g8: الفرقة الثانية / نظم المعلومات الادارية / A ---
    { id: 'lec49', subjectId: 's11', professorId: 'p28', locationId: 'l4', groupId: 'g8', day: 'السبت', startHour: 8, duration: 1, type: 'محاضرة' },
    { id: 'lec50', subjectId: 's15', professorId: 'p4', locationId: 'l4', groupId: 'g8', day: 'الأحد', startHour: 8, duration: 1, type: 'محاضرة' },
    { id: 'lec51', subjectId: 's8', professorId: 'p13', locationId: 'l4', groupId: 'g8', day: 'الاثنين', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec52', subjectId: 's14', professorId: 'p30', locationId: 'l5', groupId: 'g8', day: 'الثلاثاء', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec53', subjectId: 's12', professorId: 'p32', locationId: 'l5', groupId: 'g8', day: 'الأربعاء', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec54', subjectId: 's17', professorId: 'p39', locationId: 'l13', groupId: 'g8', day: 'الخميس', startHour: 9, duration: 2, type: 'معمل' },

    // --- Group g9: الفرقة الثانية / نظم المعلومات الادارية / B ---
    { id: 'lec55', subjectId: 's11', professorId: 'p28', locationId: 'l5', groupId: 'g9', day: 'السبت', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec56', subjectId: 's15', professorId: 'p4', locationId: 'l5', groupId: 'g9', day: 'الأحد', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec57', subjectId: 's8', professorId: 'p13', locationId: 'l5', groupId: 'g9', day: 'الاثنين', startHour: 11, duration: 1, type: 'محاضرة' },
    { id: 'lec58', subjectId: 's14', professorId: 'p30', locationId: 'l6', groupId: 'g9', day: 'الثلاثاء', startHour: 11, duration: 1, type: 'محاضرة' },
    { id: 'lec59', subjectId: 's17', professorId: 'p39', locationId: 'l14', groupId: 'g9', day: 'الخميس', startHour: 11, duration: 2, type: 'معمل' },

    // --- Group g10: الفرقة الثانية / محاسبة ---
    { id: 'lec60', subjectId: 's20', professorId: 'p21', locationId: 'l6', groupId: 'g10', day: 'السبت', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec61', subjectId: 's14', professorId: 'p34', locationId: 'l6', groupId: 'g10', day: 'الأحد', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec62', subjectId: 's13', professorId: 'p22', locationId: 'l6', groupId: 'g10', day: 'الاثنين', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec63', subjectId: 's7', professorId: 'p23', locationId: 'l6', groupId: 'g10', day: 'الثلاثاء', startHour: 9, duration: 1, type: 'محاضرة' },

    // --- Group g11: الفرقة الثالثة / نظم معلومات الاعمال / A ---
    { id: 'lec64', subjectId: 's19', professorId: 'p33', locationId: 'l2', groupId: 'g11', day: 'السبت', startHour: 8, duration: 1, type: 'محاضرة' },
    { id: 'lec65', subjectId: 's24', professorId: 'p36', locationId: 'l2', groupId: 'g11', day: 'السبت', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec66', subjectId: 's23', professorId: 'p38', locationId: 'l2', groupId: 'g11', day: 'الأحد', startHour: 8, duration: 1, type: 'محاضرة' },
    { id: 'lec67', subjectId: 's16', professorId: 'p27', locationId: 'l2', groupId: 'g11', day: 'الأحد', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec68', subjectId: 's12', professorId: 'p40', locationId: 'l2', groupId: 'g11', day: 'الاثنين', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec69', subjectId: 's22', professorId: 'p41', locationId: 'l15', groupId: 'g11', day: 'الثلاثاء', startHour: 9, duration: 2, type: 'معمل' },
    { id: 'lec70', subjectId: 's8', professorId: 'p12', locationId: 'l3', groupId: 'g11', day: 'الأربعاء', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec71', subjectId: 's21', professorId: 'p42', locationId: 'l3', groupId: 'g11', day: 'الخميس', startHour: 8, duration: 1, type: 'محاضرة' },

    // --- Group g12: الفرقة الثالثة / نظم معلومات الاعمال / B ---
    { id: 'lec72', subjectId: 's19', professorId: 'p33', locationId: 'l3', groupId: 'g12', day: 'السبت', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec73', subjectId: 's24', professorId: 'p36', locationId: 'l3', groupId: 'g12', day: 'السبت', startHour: 11, duration: 1, type: 'محاضرة' },
    { id: 'lec74', subjectId: 's23', professorId: 'p38', locationId: 'l4', groupId: 'g12', day: 'الأحد', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec75', subjectId: 's16', professorId: 'p27', locationId: 'l4', groupId: 'g12', day: 'الأحد', startHour: 11, duration: 1, type: 'محاضرة' },
    { id: 'lec76', subjectId: 's8', professorId: 'p12', locationId: 'l4', groupId: 'g12', day: 'الأربعاء', startHour: 11, duration: 1, type: 'محاضرة' },
    { id: 'lec77', subjectId: 's22', professorId: 'p41', locationId: 'l15', groupId: 'g12', day: 'الثلاثاء', startHour: 11, duration: 2, type: 'معمل' },
    { id: 'lec78', subjectId: 's12', professorId: 'p40', locationId: 'l4', groupId: 'g12', day: 'الاثنين', startHour: 11, duration: 1, type: 'محاضرة' },

    // --- Group g13: الفرقة الثالثة / نظم المعلومات الادارية / A ---
    { id: 'lec79', subjectId: 's19', professorId: 'p43', locationId: 'l5', groupId: 'g13', day: 'السبت', startHour: 8, duration: 1, type: 'محاضرة' },
    { id: 'lec80', subjectId: 's24', professorId: 'p44', locationId: 'l5', groupId: 'g13', day: 'الأحد', startHour: 8, duration: 1, type: 'محاضرة' },
    { id: 'lec81', subjectId: 's23', professorId: 'p35', locationId: 'l5', groupId: 'g13', day: 'الاثنين', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec82', subjectId: 's16', professorId: 'p31', locationId: 'l5', groupId: 'g13', day: 'الثلاثاء', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec83', subjectId: 's8', professorId: 'p13', locationId: 'l6', groupId: 'g13', day: 'الأربعاء', startHour: 10, duration: 1, type: 'محاضرة' },

    // --- Group g14: الفرقة الثالثة / محاسبة ---
    { id: 'lec84', subjectId: 's20', professorId: 'p23', locationId: 'l6', groupId: 'g14', day: 'السبت', startHour: 11, duration: 1, type: 'محاضرة' },
    { id: 'lec85', subjectId: 's14', professorId: 'p34', locationId: 'l6', groupId: 'g14', day: 'الأحد', startHour: 11, duration: 1, type: 'محاضرة' },
    { id: 'lec86', subjectId: 's13', professorId: 'p22', locationId: 'l7', groupId: 'g14', day: 'الاثنين', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec87', subjectId: 's24', professorId: 'p44', locationId: 'l7', groupId: 'g14', day: 'الثلاثاء', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec88', subjectId: 's23', professorId: 'p35', locationId: 'l7', groupId: 'g14', day: 'الأربعاء', startHour: 9, duration: 1, type: 'محاضرة' },

    // --- Group g15: الفرقة الرابعة / نظم معلومات الاعمال / A ---
    { id: 'lec89', subjectId: 's24', professorId: 'p1', locationId: 'l2', groupId: 'g15', day: 'السبت', startHour: 8, duration: 1, type: 'محاضرة' },
    { id: 'lec90', subjectId: 's23', professorId: 'p38', locationId: 'l2', groupId: 'g15', day: 'السبت', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec91', subjectId: 's19', professorId: 'p33', locationId: 'l2', groupId: 'g15', day: 'السبت', startHour: 13, duration: 1, type: 'محاضرة' },
    { id: 'lec92', subjectId: 's16', professorId: 'p11', locationId: 'l2', groupId: 'g15', day: 'الأحد', startHour: 8, duration: 1, type: 'محاضرة' },
    { id: 'lec93', subjectId: 's12', professorId: 'p40', locationId: 'l3', groupId: 'g15', day: 'الأحد', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec94', subjectId: 's15', professorId: 'p4', locationId: 'l3', groupId: 'g15', day: 'الاثنين', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec95', subjectId: 's22', professorId: 'p41', locationId: 'l15', groupId: 'g15', day: 'الثلاثاء', startHour: 13, duration: 2, type: 'معمل' },
    { id: 'lec96', subjectId: 's14', professorId: 'p26', locationId: 'l3', groupId: 'g15', day: 'الأربعاء', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec97', subjectId: 's8', professorId: 'p12', locationId: 'l21', groupId: 'g15', day: 'الخميس', startHour: 8, duration: 1, type: 'محاضرة' },

    // --- Group g16: الفرقة الرابعة / نظم معلومات الاعمال / B ---
    { id: 'lec98', subjectId: 's24', professorId: 'p1', locationId: 'l3', groupId: 'g16', day: 'السبت', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec99', subjectId: 's23', professorId: 'p38', locationId: 'l3', groupId: 'g16', day: 'السبت', startHour: 11, duration: 1, type: 'محاضرة' },
    { id: 'lec100', subjectId: 's19', professorId: 'p43', locationId: 'l4', groupId: 'g16', day: 'الأحد', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec101', subjectId: 's16', professorId: 'p11', locationId: 'l4', groupId: 'g16', day: 'الأحد', startHour: 11, duration: 1, type: 'محاضرة' },
    { id: 'lec102', subjectId: 's22', professorId: 'p41', locationId: 'l15', groupId: 'g16', day: 'الثلاثاء', startHour: 9, duration: 2, type: 'معمل' },
    { id: 'lec103', subjectId: 's8', professorId: 'p12', locationId: 'l21', groupId: 'g16', day: 'الخميس', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec104', subjectId: 's15', professorId: 'p4', locationId: 'l4', groupId: 'g16', day: 'الاثنين', startHour: 11, duration: 1, type: 'محاضرة' },

    // --- Group g17: الفرقة الرابعة / نظم المعلومات الادارية / A ---
    { id: 'lec105', subjectId: 's24', professorId: 'p44', locationId: 'l5', groupId: 'g17', day: 'السبت', startHour: 8, duration: 1, type: 'محاضرة' },
    { id: 'lec106', subjectId: 's23', professorId: 'p35', locationId: 'l5', groupId: 'g17', day: 'الأحد', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec107', subjectId: 's19', professorId: 'p43', locationId: 'l5', groupId: 'g17', day: 'الاثنين', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec108', subjectId: 's16', professorId: 'p31', locationId: 'l6', groupId: 'g17', day: 'الثلاثاء', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec109', subjectId: 's12', professorId: 'p40', locationId: 'l6', groupId: 'g17', day: 'الأربعاء', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec110', subjectId: 's22', professorId: 'p41', locationId: 'l23', groupId: 'g17', day: 'الخميس', startHour: 9, duration: 2, type: 'معمل' },

    // --- Group g18: الفرقة الرابعة / محاسبة ---
    { id: 'lec111', subjectId: 's20', professorId: 'p23', locationId: 'l7', groupId: 'g18', day: 'السبت', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec112', subjectId: 's14', professorId: 'p34', locationId: 'l7', groupId: 'g18', day: 'الأحد', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec113', subjectId: 's13', professorId: 'p22', locationId: 'l7', groupId: 'g18', day: 'الاثنين', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec114', subjectId: 's24', professorId: 'p44', locationId: 'l7', groupId: 'g18', day: 'الثلاثاء', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec115', subjectId: 's23', professorId: 'p35', locationId: 'l7', groupId: 'g18', day: 'الأربعاء', startHour: 11, duration: 1, type: 'محاضرة' },

    // Extra lectures for g1 groups to boost the count
    { id: 'lec116', subjectId: 's21', professorId: 'p42', locationId: 'l1', groupId: 'g1', day: 'الاثنين', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec117', subjectId: 's7', professorId: 'p23', locationId: 'l5', groupId: 'g2', day: 'الخميس', startHour: 8, duration: 1, type: 'محاضرة' },
    { id: 'lec118', subjectId: 's11', professorId: 'p15', locationId: 'l4', groupId: 'g3', day: 'السبت', startHour: 11, duration: 1, type: 'محاضرة' },
    { id: 'lec119', subjectId: 's21', professorId: 'p16', locationId: 'l1', groupId: 'g4', day: 'الأربعاء', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec120', subjectId: 's25', professorId: 'p14', locationId: 'l5', groupId: 'g5', day: 'الثلاثاء', startHour: 11, duration: 1, type: 'محاضرة' },
    { id: 'lec121', subjectId: 's21', professorId: 'p42', locationId: 'l2', groupId: 'g6', day: 'الثلاثاء', startHour: 8, duration: 1, type: 'محاضرة' },
    { id: 'lec122', subjectId: 's16', professorId: 'p27', locationId: 'l3', groupId: 'g7', day: 'الخميس', startHour: 9, duration: 1, type: 'محاضرة' },
    { id: 'lec123', subjectId: 's21', professorId: 'p42', locationId: 'l4', groupId: 'g8', day: 'الثلاثاء', startHour: 11, duration: 1, type: 'محاضرة' },
    { id: 'lec124', subjectId: 's12', professorId: 'p32', locationId: 'l5', groupId: 'g9', day: 'الأربعاء', startHour: 11, duration: 1, type: 'محاضرة' },
    { id: 'lec125', subjectId: 's11', professorId: 'p28', locationId: 'l1', groupId: 'g10', day: 'السبت', startHour: 11, duration: 1, type: 'محاضرة' },
    { id: 'lec126', subjectId: 's21', professorId: 'p42', locationId: 'l2', groupId: 'g11', day: 'الثلاثاء', startHour: 13, duration: 1, type: 'محاضرة' },
    { id: 'lec127', subjectId: 's21', professorId: 'p42', locationId: 'l3', groupId: 'g12', day: 'الخميس', startHour: 8, duration: 1, type: 'محاضرة' },
    { id: 'lec128', subjectId: 's12', professorId: 'p40', locationId: 'l5', groupId: 'g13', day: 'الخميس', startHour: 8, duration: 1, type: 'محاضرة' },
    { id: 'lec129', subjectId: 's22', professorId: 'p41', locationId: 'l15', groupId: 'g14', day: 'الخميس', startHour: 9, duration: 2, type: 'معمل' },
    { id: 'lec130', subjectId: 's21', professorId: 'p42', locationId: 'l2', groupId: 'g15', day: 'الثلاثاء', startHour: 8, duration: 1, type: 'محاضرة' },
    { id: 'lec131', subjectId: 's21', professorId: 'p42', locationId: 'l3', groupId: 'g16', day: 'الأربعاء', startHour: 13, duration: 1, type: 'محاضرة' },
    { id: 'lec132', subjectId: 's21', professorId: 'p42', locationId: 'l5', groupId: 'g17', day: 'الثلاثاء', startHour: 11, duration: 1, type: 'محاضرة' },
    { id: 'lec133', subjectId: 's22', professorId: 'p41', locationId: 'l23', groupId: 'g18', day: 'الثلاثاء', startHour: 13, duration: 2, type: 'معمل' },

    // Online lectures for various groups
    { id: 'lec134', subjectId: 's4', professorId: 'p9', locationId: 'l1', groupId: 'g6', day: 'الاثنين', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec135', subjectId: 's4', professorId: 'p9', locationId: 'l1', groupId: 'g7', day: 'الاثنين', startHour: 12, duration: 1, type: 'محاضرة' },
    { id: 'lec136', subjectId: 's4', professorId: 'p9', locationId: 'l1', groupId: 'g8', day: 'السبت', startHour: 12, duration: 1, type: 'محاضرة' },
    { id: 'lec137', subjectId: 's4', professorId: 'p9', locationId: 'l1', groupId: 'g9', day: 'السبت', startHour: 13, duration: 1, type: 'محاضرة' },
    { id: 'lec138', subjectId: 's5', professorId: 'p10', locationId: 'l1', groupId: 'g3', day: 'الخميس', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec139', subjectId: 's5', professorId: 'p10', locationId: 'l1', groupId: 'g4', day: 'الخميس', startHour: 11, duration: 1, type: 'محاضرة' },
    { id: 'lec140', subjectId: 's3', professorId: 'p8', locationId: 'l1', groupId: 'g5', day: 'الأحد', startHour: 11, duration: 1, type: 'محاضرة' },
    { id: 'lec141', subjectId: 's6', professorId: 'p3', locationId: 'l1', groupId: 'g3', day: 'الأحد', startHour: 12, duration: 1, type: 'محاضرة' },
    { id: 'lec142', subjectId: 's6', professorId: 'p3', locationId: 'l1', groupId: 'g4', day: 'الأحد', startHour: 13, duration: 1, type: 'محاضرة' },
    { id: 'lec143', subjectId: 's2', professorId: 'p5', locationId: 'l1', groupId: 'g8', day: 'الاثنين', startHour: 13, duration: 1, type: 'محاضرة' },
    { id: 'lec144', subjectId: 's1', professorId: 'p20', locationId: 'l1', groupId: 'g6', day: 'الأربعاء', startHour: 13, duration: 1, type: 'محاضرة' },
    { id: 'lec145', subjectId: 's1', professorId: 'p20', locationId: 'l1', groupId: 'g7', day: 'الخميس', startHour: 13, duration: 1, type: 'محاضرة' },
    { id: 'lec146', subjectId: 's9', professorId: 'p18', locationId: 'l1', groupId: 'g5', day: 'الخميس', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec147', subjectId: 's13', professorId: 'p22', locationId: 'l1', groupId: 'g11', day: 'الخميس', startHour: 8, duration: 1, type: 'محاضرة' },
    { id: 'lec148', subjectId: 's13', professorId: 'p22', locationId: 'l1', groupId: 'g12', day: 'الخميس', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec149', subjectId: 's14', professorId: 'p26', locationId: 'l1', groupId: 'g13', day: 'السبت', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec150', subjectId: 's15', professorId: 'p4', locationId: 'l1', groupId: 'g14', day: 'السبت', startHour: 13, duration: 1, type: 'محاضرة' },
    { id: 'lec151', subjectId: 's15', professorId: 'p4', locationId: 'l1', groupId: 'g17', day: 'الخميس', startHour: 8, duration: 1, type: 'محاضرة' },
    { id: 'lec152', subjectId: 's15', professorId: 'p4', locationId: 'l1', groupId: 'g18', day: 'الخميس', startHour: 10, duration: 1, type: 'محاضرة' },
    { id: 'lec153', subjectId: 's11', professorId: 'p28', locationId: 'l1', groupId: 'g10', day: 'الثلاثاء', startHour: 13, duration: 1, type: 'محاضرة' },
    { id: 'lec154', subjectId: 's25', professorId: 'p14', locationId: 'l1', groupId: 'g6', day: 'السبت', startHour: 13, duration: 1, type: 'محاضرة' },
    { id: 'lec155', subjectId: 's25', professorId: 'p14', locationId: 'l1', groupId: 'g7', day: 'الأحد', startHour: 13, duration: 1, type: 'محاضرة' },
    { id: 'lec156', subjectId: 's10', professorId: 'p1', locationId: 'l1', groupId: 'g11', day: 'السبت', startHour: 12, duration: 1, type: 'محاضرة' },
    { id: 'lec157', subjectId: 's10', professorId: 'p1', locationId: 'l1', groupId: 'g12', day: 'الأحد', startHour: 13, duration: 1, type: 'محاضرة' },
    { id: 'lec158', subjectId: 's10', professorId: 'p1', locationId: 'l1', groupId: 'g15', day: 'الثلاثاء', startHour: 11, duration: 1, type: 'محاضرة' },
    { id: 'lec159', subjectId: 's10', professorId: 'p1', locationId: 'l1', groupId: 'g16', day: 'الأربعاء', startHour: 8, duration: 1, type: 'محاضرة' },
    { id: 'lec160', subjectId: 's10', professorId: 'p1', locationId: 'l1', groupId: 'g17', day: 'الاثنين', startHour: 13, duration: 1, type: 'محاضرة' },
    { id: 'lec161', subjectId: 's10', professorId: 'p1', locationId: 'l1', groupId: 'g18', day: 'الخميس', startHour: 12, duration: 1, type: 'محاضرة' },
  ],
}
